name: MixBukkit
main: io.github.mosadie.MixBukkit.MixBukkit
version: 1.0
author: MoSadie
description: Manages a connection to Mixer to make Mixer Interactive compatable Bukkit plugins.
commands:
  mixbukkit:
    description: Main command of the plugin. Allows you to configure the plugin.
    usage: /<command> <help or debug>
    aliases: mb